name: Deploy to Production

# on:
#   push:
#     branches:
#       - main

on: "workflow_dispatch"


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
      SSH_USER_PASS: ${{ secrets.SSH_USER_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
        
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_USER_PASS }}
          script: |
            set -e  # Exit immediately if a command exits with a non-zero status
            
            cd /home/cognova-app/htdocs/app.cognova.io || exit 1
            
            # Configure Git credentials
            git config --global credential.helper store
            echo "https://oauth2:${{ env.GIT_TOKEN }}@github.com" > ~/.git-credentials
            
            # Stash current changes
            git stash || exit 1

            # Pull latest changes
            git pull origin main || exit 1
            
            # Install dependencies
            npm install || exit 1
            
            # Build the application
            npm run build || exit 1
            
            # Restart PM2 process
            pm2 restart ecosystem.config.js || exit 1
            
            # Clean up credentials for security
            FILE=~/.git-credentials

            # Check if the file exists and remove it
            if [ -f "$FILE" ]; then
                rm "$FILE" || echo "Warning: Failed to delete credentials file"
            fi
            
            echo "Deployment completed successfully"
